#include <stdio.h>
#include <time.h>
#include <string.h>

#include "tec.h"
#include "aux/config.h"
#include "aux/toggle.h"

/* Note: should be static cuz args->task point to it.  */
static char gentask[IDSIZ + 1];

static int generate_task(tec_arg_t *args, char **argv, int argv_idx)
{
    args->taskid = gentask;
    for (register unsigned int i = 1; i < IDLIMIT; ++i) {
        sprintf(gentask, IDFMT, i);
        if (tec_task_exist(teccfg.base.task, args) != LIBTEC_OK) {
            argv[argv_idx] = gentask;
            return 0;
        }
    }
    return 1;
}

static int generate_units(tec_ctx_t *ctx, char *env, char *task)
{
    char date[BUFSIZ + 1];
    struct tec_unit *units = NULL;
    time_t rawtime = time(NULL);
    const char timefmt[] = "%Y%m%d";
    struct tm *timeinfo = localtime(&rawtime);
    char desc[100] = "autogenerated desciption for ";
    char *unitvals[] = { "mid", "task", date, desc, };

    strcat(desc, task);
    strftime(date, BUFSIZ, timefmt, timeinfo);

    for (int i = 0; i < nunitkey; ++i)
        units = tec_unit_add(units, unitkeys[i], unitvals[i]);
    ctx->units = units;
    return 0;
}

int tec_cli_add(int argc, const char **argv, tec_ctx_t *ctx)
{
    tec_arg_t args;
    tec_argvec_t argvec;
    const char *errfmt;
    int c, i, retcode, status;
    int opt_quiet, opt_help, opt_cd_dir, opt_cd_toggle;

    retcode = LIBTEC_OK;
    opt_quiet = opt_help = false;
    opt_cd_dir = opt_cd_toggle = true;
    args.env = args.desk = args.taskid = NULL;
    errfmt = "cannot create task '%s': %s";

    argvec_init(&argvec);
    argvec_parse(&argvec, argc, argv);
    while ((c = getopt(argvec.used, argvec.argv, ":d:e:hqnN")) != -1) {
        switch (c) {
        case 'd':
            args.desk = optarg;
            break;
        case 'e':
            args.env = optarg;
            break;
        case 'h':
            opt_help = true;
            break;
        case 'n':
            opt_cd_toggle = false;
            break;
        case 'q':
            opt_quiet = true;
            break;
        case 'N':
            opt_cd_dir = false;
            opt_cd_toggle = false;
            break;
        case ':':
            return elog(1, "option `-%c' requires an argument", optopt);
        default:
            return elog(1, "invalid option `-%c'", optopt);
        }
    }
    i = optind;

    if (opt_help == true)
        return help_usage("add");

    if ((status = check_arg_env(&args, errfmt, opt_quiet)))
        return status;
    else if ((status = check_arg_desk(&args, errfmt, opt_quiet)))
        return status;
    else if (optind == argc && generate_task(&args, argvec.argv, i)) {
        if (opt_quiet == false)
            elog(1, "could not generate task ID: limit is %d", IDLIMIT);
        return 1;
    }

    do {
        args.taskid = argvec.argv[i];

        if ((status = tec_task_valid(teccfg.base.task, &args))) {
            if (opt_quiet == false)
                elog(status, errfmt, args.taskid, tec_strerror(status));
            retcode = status == LIBTEC_OK ? retcode : status;
            continue;
        } else if (is_valid_length(args.taskid, IDSIZ) == false) {
            if (opt_quiet == false)
                elog(status, errfmt, args.taskid, "task ID is too long");
            retcode = status == LIBTEC_OK ? retcode : status;
            continue;
        } else if (!(status = tec_task_exist(teccfg.base.task, &args))) {
            if (opt_quiet == false)
                elog(1, errfmt, args.taskid, tec_strerror(LIBTEC_ARG_EXISTS));
            retcode = !(status == LIBTEC_OK) ? retcode : !status;
            continue;
        } else if (generate_units(ctx, args.env, args.taskid)) {
            if (opt_quiet == false)
                elog(1, errfmt, args.taskid, "unit generation failed");
            retcode = status == LIBTEC_OK ? retcode : status;
            continue;
        }

        if ((status = tec_task_add(teccfg.base.task, &args, ctx))) {
            if (opt_quiet == false)
                elog(status, errfmt, args.taskid, tec_strerror(status));
        } else if ((status = hook_action(&args, "add"))) {
            if (opt_quiet == false)
                elog(1, errfmt, args.taskid, "failed to execute hooks");
        } else if (opt_cd_toggle == true) {
            if ((status = toggle_task_set_curr(teccfg.base.task, &args))) {
                if (opt_quiet == false)
                    elog(status, "could not update toggles");
            }
        }
        ctx->units = tec_unit_free(ctx->units);
        retcode = status == LIBTEC_OK ? retcode : status;
    } while (++i < argvec.used);

    if (retcode == LIBTEC_OK && opt_cd_dir)
        retcode = tec_pwd_task(&args) == LIBTEC_OK ? retcode : status;

    argvec_free(&argvec);
    return retcode;
}
