#include <ctype.h>
#include <string.h>
#include <dirent.h>

#include "tec.h"
#include "aux/toggle.h"
#include "aux/config.h"

static int valid_desc(const char *val)
{
    if (!isalnum(*val++))
        return false;
    for (; *val; ++val)
        if (!(isalnum(*val) || isspace(*val) || *val == '_' || *val == '-'))
            return false;
    return isalnum(*--val) != 0;
}

static int generate_units(tec_ctx_t *ctx, char *desk)
{
    struct tec_unit *units = NULL;
    char desc[100] = "autogenerated desciption for desk ";

    strcat(desc, desk);
    units = tec_unit_add(units, "desc", desc);
    ctx->units = units;
    return 0;
}

// TODO: add support to generate desk name
static int _desk_add(int argc, char **argv, tec_ctx_t *ctx)
{
    char c;
    tec_arg_t args;
    const char *errfmt = "cannot add desk '%s': %s";
    int i, quiet, showhelp, status;

    status = LIBTEC_OK;
    showhelp = quiet = false;
    args.env = args.desk = args.taskid = NULL;
    while ((c = getopt(argc, argv, ":hnp:q")) != -1) {
        switch (c) {
        case 'e':
            args.env = optarg;
            break;
        case 'h':
            showhelp = true;
            break;
        case 'n':
            //opt.desk_switch = false;
            break;
        case 'q':
            quiet = true;
            break;
        case ':':
            return elog(1, "option `-%c' requires an argument", optopt);
        default:
            return elog(1, "invalid option `-%c'", optopt);
        }
    }

    if (showhelp)
        return help_usage("desk-add");

    if (optind == argc)
        return elog(1, "desk name required");
    else if ((ctx->column = generate_column("todo")) == NULL) {
        if (quiet == false)
            elog(1, "could not generate column");
        return 1;
    }

    if ((status = toggle_env_get_curr(teccfg.base.task, &args))) {
        return status;
    }

    for (i = optind; i < argc; ++i) {
        args.desk = argv[i];

        if (generate_units(ctx, args.desk)) {
            if (quiet == false)
                elog(1, errfmt, args.env, "unit generation failed");
            continue;
        }
        if ((status = tec_desk_add(teccfg.base.task, &args, ctx))) {
            if (quiet == false)
                elog(1, errfmt, argv[i], tec_strerror(status));
            ctx->units = tec_unit_free(ctx->units);
            continue;
        }
        // TODO: add hooks
        ctx->units = tec_unit_free(ctx->units);
    }

    ctx->column = tec_unit_free(ctx->column);
    //return status == LIBTEC_OK ? tec_pwd_desk(&args) : 1;
    return 0;
}

static int _desk_rm(int argc, char **argv, tec_ctx_t *ctx)
{
    char c;
    tec_arg_t args;
    const char *errfmt = "cannot remove: %s";
    int i, choice, quiet, showhelp, showprompt, status;

    showprompt = true;
    status = LIBTEC_OK;
    choice = quiet = showhelp = false;
    args.env = args.desk = args.taskid = NULL;
    while ((c = getopt(argc, argv, ":hnq")) != -1) {
        switch (c) {
        case 'h':
            showhelp = true;
            break;
        case 'n':
            showprompt = false;
            break;
        case 'q':
            quiet = true;
            break;
        case ':':
            return elog(1, "option `-%c' requires an argument", optopt);
        default:
            return elog(1, "invalid option `-%c'", optopt);
        }
    }

    if (showhelp)
        return help_usage("desk-rm");

    i = optind;
    do {
        args.desk = argv[i];

        if (showprompt) {
            /* TODO: show desk name.  */
            printf("Are you sure to remove desk(s)? [y/N] ");
            if ((choice = getchar()) != 'y' && choice != 'Y')
                continue;
        }

        if ((status = tec_desk_del(teccfg.base.task, &args, ctx))) {
            if (quiet == false)
                elog(status, errfmt, argv[i], tec_strerror(status));
        }
    } while (++i < argc);

    // TODO: update current directory if current env got deleted.
    return status == LIBTEC_OK ? tec_pwd_desk(&args) : status;
}

// TODO: show tasks in desk
static int _desk_ls(int argc, char **argv, tec_ctx_t *ctx)
{
    tec_arg_t args;
    int c, i, quiet, status;
    int opt_help;
    const char *errfmt = "cannot list desk(s) '%s': %s";

    quiet = false;
    opt_help = false;
    while ((c = getopt(argc, argv, ":hq")) != -1) {
        switch (c) {
        case 'q':
            quiet = true;
            break;
        case 'h':
            opt_help = true;
            break;
        case ':':
            return elog(1, "option `-%c' requires an argument", optopt);
        default:
            return elog(1, "invalid option `-%c'", optopt);
        }
    }

    if (opt_help == true)
        return help_usage("desk-ls");

    if ((status = toggle_env_get_curr(teccfg.base.task, &args))) {
        if (quiet == false)
            elog(status, errfmt, "NOCURR", "no current env");
        return status;
    } else if ((status = tec_env_valid(teccfg.base.task, &args))) {
        if (quiet == false)
            elog(status, errfmt, args.desk, tec_strerror(status));
        return status;
    }

    i = optind;
    do {
        args.desk = argv[i];

        if (check_arg_desk(&args, errfmt, quiet))
            continue;
        if ((status = tec_desk_list(teccfg.base.task, &args, ctx))) {
            if (quiet == false)
                elog(status, errfmt, args.desk, tec_strerror(status));
            continue;
        }

        for (tec_list_t * obj = ctx->list; obj != NULL; obj = obj->next) {
            LIST_OBJ_UNITS("mark", obj->name, "", "some desk description");
        }
        ctx->list = tec_list_free(ctx->list);
    } while (++i < argc);
    return status;
}

static int _desk_mv(int argc, char **argv, tec_ctx_t *ctx)
{
    return elog(1, "%s: under development", __FUNCTION__);
}

static int _desk_set(int argc, char **argv, tec_ctx_t *ctx)
{
    tec_arg_t args;
    int atleast_one_key_set;
    int c, i, quiet, showhelp;
    const char *errfmt = "could not set desk unit value '%s': %s";

    quiet = showhelp = false;
    atleast_one_key_set = false;
    args.env = args.desk = args.taskid = NULL;
    while ((c = getopt(argc, argv, ":d:hq")) != -1) {
        switch (c) {
        case 'd':
            if (valid_desc(optarg) == false) {
                elog(1, "invalid description '%s'", optarg);
                help_usage("desk-set");
                return 1;
            }
            atleast_one_key_set = true;
            ctx->units = tec_unit_add(ctx->units, "desc", optarg);
            break;
        case 'h':
            showhelp = true;
            break;
        case 'q':
            quiet = true;
            break;
        case ':':
            return elog(1, "option `-%c' requires an argument", optopt);
        default:
            return elog(1, "invalid option `-%c'", optopt);
        }
    }

    if (showhelp)
        return help_usage("desk-set");
    if (atleast_one_key_set == false) {
        elog(1, "gotta supply one of the options");
        help_usage("desk-set");
        return 1;
    }

    i = optind;
    do {
        int status;
        args.desk = argv[i];

        if ((status = tec_desk_set(teccfg.base.task, &args, ctx))) {
            if (quiet == false)
                elog(status, errfmt, argv[i], tec_strerror(status));
        }
    } while (++i < argc);

    ctx->units = tec_unit_free(ctx->units);
    return 0;
}

static int _desk_cat(int argc, char **argv, tec_ctx_t *ctx)
{
    tec_arg_t args;
    int c, i, quiet, showhelp, status;
    struct tec_unit *units, *unitpgn;
    const char *errfmt = "cannot show env units '%s': %s";

    units = unitpgn = NULL;
    quiet = showhelp = false;
    args.env = args.desk = args.taskid = NULL;
    while ((c = getopt(argc, argv, ":hq")) != -1) {
        switch (c) {
        case 'h':
            showhelp = true;
            break;
        case 'q':
            quiet = true;
            break;
        case ':':
            return elog(1, "option `-%c' requires an argument", optopt);
        default:
            return elog(1, "invalid option `-%c'", optopt);
        }
    }

    if (showhelp)
        return help_usage("desk-cat");

    i = optind;
    do {
        args.desk = argv[i];
        if ((status = tec_desk_get(teccfg.base.task, &args, ctx)) != LIBTEC_OK) {
            if (quiet == false)
                elog(status, errfmt, argv[i], tec_strerror(status));
            continue;
        }

        printf("%-7s : %s\n", "desk", args.desk);
        for (units = ctx->units; units; units = units->next)
            printf("%-7s : %s\n", units->key, units->val);

        // TODO: add plugin output
    } while (++i < argc);

    return status;
}

static int _desk_cd(int argc, char **argv, tec_ctx_t *ctx)
{
    tec_arg_t args;
    char alias[BRDSIZ + 1] = { 0 };
    int c, i, quiet, retcode, showhelp, status;
    const char *errfmt = "cannot switch to '%s': %s";
    int switch_toggle, switch_dir;

    retcode = LIBTEC_OK;
    quiet = showhelp = false;
    switch_toggle = switch_dir = true;
    args.env = args.desk = args.taskid = NULL;
    while ((c = getopt(argc, argv, ":hnp:qN")) != -1) {
        switch (c) {
        case 'h':
            showhelp = true;
            break;
        case 'n':
            switch_toggle = false;
            break;
        case 'e':
            args.env = optarg;
            break;
        case 'q':
            quiet = true;
            break;
        case 'N':
            switch_dir = false;
            switch_toggle = false;
            break;
        case ':':
            return elog(1, "option `-%c' requires an argument", optopt);
        default:
            return elog(1, "invalid option `-%c'", optopt);
        }
    }

    if (showhelp)
        return help_usage("desk-cd");

    if ((status = check_arg_env(&args, errfmt, quiet)))
        return status;

    i = optind;

    /* Check that alias '-' is not passed among task IDs.  */
    for (int idx = 1; idx < argc; ++idx) {
        if (strcmp(argv[idx], "-") == 0 && argc > 2)
            return elog(1, "alias '-' is used alone");
    }

    do {
        args.desk = argv[i];
        retcode = status == LIBTEC_OK ? retcode : status;

        /* Alias to switch to previous environment.  */
        if (argv[i] && strcmp("-", argv[i]) == 0) {
            args.desk = NULL;   /* unset desk name.  */
            if ((status = toggle_desk_get_prev(teccfg.base.task, &args)))
                return elog(1, errfmt, "PREV", "no previous environment");
            args.taskid = strncpy(alias, args.desk, BRDSIZ);
        }
        // TODO: add hooks after env check and before switch toggle

        if ((status = check_arg_desk(&args, errfmt, quiet))) {
            return status;
        } else if (switch_toggle == true) {
            if (toggle_desk_set_curr(teccfg.base.task, &args) && quiet == false) {
                if (quiet == false)
                    elog(1, "could not update toggles");
                status = 1;     /* TODO: use cli return codes.  */
                continue;
            }
        }
    } while (++i < argc);

    retcode = status == LIBTEC_OK ? retcode : status;
    return retcode == LIBTEC_OK && switch_dir ? tec_pwd_desk(&args) : retcode;
}

static const builtin_t desk_commands[] = {
    {.name = "add",.func = &_desk_add},
    {.name = "cat",.func = &_desk_cat},
    {.name = "cd",.func = &_desk_cd},
    {.name = "ls",.func = &_desk_ls},
    {.name = "mv",.func = &_desk_mv},
    {.name = "rm",.func = &_desk_rm},
    {.name = "set",.func = &_desk_set},
};

int tec_cli_desk(int argc, char **argv, tec_ctx_t *ctx)
{
    char *cmd = argv[1] != NULL ? argv[1] : "ls";

    for (int i = 0; i < ARRAY_SIZE(desk_commands); ++i)
        if (strcmp(cmd, desk_commands[i].name) == 0)
            return desk_commands[i].func(argc - 1, argv + 1, ctx);

    return elog(1, "'%s': no such desk subcommand", cmd);
}
