#include <ctype.h>
#include <string.h>
#include <dirent.h>

#include "tec.h"
#include "aux/toggle.h"
#include "aux/config.h"

static int valid_desc(const char *val)
{
    if (!isalnum(*val++))
        return false;
    for (; *val; ++val)
        if (!(isalnum(*val) || isspace(*val) || *val == '_' || *val == '-'))
            return false;
    return isalnum(*--val) != 0;
}

static int generate_units(tec_ctx_t *ctx, char *desk)
{
    struct tec_unit *units = NULL;
    char desc[100] = "autogenerated desciption for desk ";

    strcat(desc, desk);
    units = tec_unit_add(units, "desc", desc);
    ctx->units = units;
    return 0;
}

// TODO: add support to generate desk name
static int _desk_add(int argc, char **argv, tec_ctx_t *ctx)
{
    char c;
    tec_arg_t args;
    int i, retcode, status;
    const char *errfmt = "cannot add desk '%s': %s";
    int opt_quiet, opt_help, opt_cd_dir, opt_cd_toggle;

    retcode = LIBTEC_OK;
    opt_help = opt_quiet = false;
    opt_cd_dir = opt_cd_toggle = true;
    args.env = args.desk = args.taskid = NULL;
    while ((c = getopt(argc, argv, ":e:hnqN")) != -1) {
        switch (c) {
        case 'e':
            args.env = optarg;
            break;
        case 'h':
            opt_help = true;
            break;
        case 'n':
            opt_cd_toggle = false;
            break;
        case 'q':
            opt_quiet = true;
            break;
        case 'N':
            opt_cd_dir = false;
            opt_cd_toggle = false;
        case ':':
            return elog(1, "option `-%c' requires an argument", optopt);
        default:
            return elog(1, "invalid option `-%c'", optopt);
        }
    }
    i = optind;

    if (opt_help)
        return help_usage("desk-add");

    if (optind == argc)
        return elog(1, "desk name required");
    else if ((ctx->column = generate_column("todo")) == NULL) {
        if (opt_quiet == false)
            elog(1, "could not generate column");
        return 1;
    }

    if ((status = check_arg_env(&args, errfmt, opt_quiet)))
        return status;

    do {
        args.desk = argv[i];

        if (generate_units(ctx, args.desk)) {
            if (opt_quiet == false)
                elog(1, errfmt, args.desk, "unit generation failed");
            retcode = status == LIBTEC_OK ? retcode : status;
            continue;
        }

        if ((status = tec_desk_add(teccfg.base.task, &args, ctx))) {
            if (opt_quiet == false)
                elog(1, errfmt, argv[i], tec_strerror(status));
            ctx->units = tec_unit_free(ctx->units);
        } else if ((status = hook_action(&args, "desk-add"))) {
            if (opt_quiet == false)
                elog(1, errfmt, args.taskid, "failed to execute hooks");
        } else if (opt_cd_toggle == true) {
            if ((status = toggle_desk_set_curr(teccfg.base.task, &args))) {
                if (opt_quiet == false)
                    elog(status, "could not update toggles");
            }
        }
        ctx->units = tec_unit_free(ctx->units);
        ctx->column = tec_unit_free(ctx->column);
        retcode = status == LIBTEC_OK ? retcode : status;
    } while (++i < argc);
    return retcode == LIBTEC_OK && opt_cd_dir ? tec_pwd_desk(&args) : retcode;
}

static int _desk_rm(int argc, char **argv, tec_ctx_t *ctx)
{
    tec_arg_t args;
    int c, i, retcode, status;
    int opt_quiet, opt_help;
    const char *errfmt = "cannot remove: %s";
    int opt_ask_once, opt_ask_every, opt_verbose;

    retcode = LIBTEC_OK;
    opt_ask_every = true;       /* prompt before every removal.  */
    opt_ask_once = false;       /* prompt before once for all desks.  */
    args.env = args.desk = args.taskid = NULL;
    opt_quiet = opt_help = opt_verbose = false;
    while ((c = getopt(argc, argv, ":fhiqvI")) != -1) {
        switch (c) {
        case 'f':
            opt_ask_every = false;
            opt_ask_once = false;
            break;
        case 'h':
            opt_help = true;
            break;
        case 'i':
            opt_ask_every = true;
            opt_ask_once = false;
            break;
        case 'q':
            opt_quiet = true;
            break;
        case 'v':
            opt_verbose = false;
            break;
        case 'I':
            opt_ask_every = false;
            opt_ask_once = true;
            break;
        case ':':
            return elog(1, "option `-%c' requires an argument", optopt);
        default:
            return elog(1, "invalid option `-%c'", optopt);
        }
    }
    i = optind;

    if (opt_help)
        return help_usage("desk-rm");

    if ((status = check_arg_env(&args, errfmt, opt_quiet)))
        return status;

    if (opt_ask_once == true) {
        printf("Are you sure to remove desk(s)? [y/N] ");
        if (tec_cli_get_user_choice() == false) {
            return LIBTEC_OK;
        }
    }

    do {
        args.desk = argv[i];

        if ((status = check_arg_desk(&args, errfmt, opt_quiet))) {
            retcode = status == LIBTEC_OK ? retcode : status;
            continue;
        } else if (opt_ask_every == true) {
            printf("Are you sure to remove desk '%s'? [y/N] ", args.desk);
            if (tec_cli_get_user_choice() == false) {
                continue;
            }
        }

        if ((status = hook_action(&args, "desk-rm"))) {
            if (opt_quiet == false)
                elog(1, errfmt, args.desk, "failed to execute hooks");
        } else if ((status = tec_desk_del(teccfg.base.task, &args, ctx))) {
            if (opt_quiet == false)
                elog(status, errfmt, argv[i], tec_strerror(status));
        }

        /* TODO: handle current and previos task IDs. */

        if (opt_verbose == true)
            llog(0, "removed desk '%s'", args.taskid);
        retcode = status == LIBTEC_OK ? retcode : status;
    } while (++i < argc);

    // TODO: update current directory if current env got deleted.
    return retcode == LIBTEC_OK ? tec_pwd_desk(&args) : retcode;
}

// TODO: show tasks in desk
static int _desk_ls(int argc, char **argv, tec_ctx_t *ctx)
{
    tec_arg_t args;
    int c, i, status;
    int opt_help, opt_quiet;
    const char *errfmt = "cannot list desk(s) '%s': %s";

    opt_help = opt_quiet = false;
    while ((c = getopt(argc, argv, ":hq")) != -1) {
        switch (c) {
        case 'q':
            opt_quiet = true;
            break;
        case 'h':
            opt_help = true;
            break;
        case ':':
            return elog(1, "option `-%c' requires an argument", optopt);
        default:
            return elog(1, "invalid option `-%c'", optopt);
        }
    }

    if (opt_help == true)
        return help_usage("desk-ls");

    if ((status = check_arg_env(&args, errfmt, opt_quiet)))
        return status;

    i = optind;
    do {
        args.desk = argv[i];

        if (check_arg_desk(&args, errfmt, opt_quiet))
            continue;
        if ((status = tec_desk_list(teccfg.base.task, &args, ctx))) {
            if (opt_quiet == false)
                elog(status, errfmt, args.desk, tec_strerror(status));
            continue;
        }

        for (tec_list_t * obj = ctx->list; obj != NULL; obj = obj->next) {
            LIST_OBJ_UNITS("mark", obj->name, "", "some desk description");
        }
        ctx->list = tec_list_free(ctx->list);
    } while (++i < argc);
    return status;
}

static int _desk_mv(int argc, char **argv, tec_ctx_t *ctx)
{
    return elog(1, "%s: under development", __FUNCTION__);
}

static int _desk_set(int argc, char **argv, tec_ctx_t *ctx)
{
    tec_arg_t args;
    int atleast_one_key_set;
    int opt_quiet, opt_help;
    int c, i, retcode, status;
    const char *errfmt = "could not set desk unit value '%s': %s";

    retcode = LIBTEC_OK;
    opt_quiet = opt_help = false;
    atleast_one_key_set = false;
    args.env = args.desk = args.taskid = NULL;
    while ((c = getopt(argc, argv, ":hqD:")) != -1) {
        switch (c) {
        case 'h':
            opt_help = true;
            break;
        case 'q':
            opt_quiet = true;
            break;
        case 'D':
            if (valid_desc(optarg) == false) {
                elog(1, "invalid description '%s'", optarg);
                help_usage("desk-set");
                return 1;
            }
            atleast_one_key_set = true;
            ctx->units = tec_unit_add(ctx->units, "desc", optarg);
            break;
        case ':':
            return elog(1, "option `-%c' requires an argument", optopt);
        default:
            return elog(1, "invalid option `-%c'", optopt);
        }
    }

    if (opt_help)
        return help_usage("desk-set");
    if (atleast_one_key_set == false) {
        elog(1, "gotta supply one of the options");
        help_usage("desk-set");
        return 1;
    }

    if ((status = check_arg_env(&args, errfmt, opt_quiet)))
        return status;

    i = optind;
    do {
        args.desk = argv[i];

        if ((status = check_arg_desk(&args, errfmt, opt_quiet))) {
            ;
        } else if ((status = tec_desk_set(teccfg.base.task, &args, ctx))) {
            if (opt_quiet == false)
                elog(status, errfmt, argv[i], tec_strerror(status));
        } else if ((status = hook_action(&args, "desk-set"))) {
            if (opt_quiet == false)
                elog(1, errfmt, args.taskid, "failed to execute hooks");
        }

        ctx->units = tec_unit_free(ctx->units);
        retcode = status == LIBTEC_OK ? retcode : status;
    } while (++i < argc);
    return retcode;
}

static int _desk_cat(int argc, char **argv, tec_ctx_t *ctx)
{
    tec_arg_t args;
    int opt_quiet, opt_help;
    int c, i, retcode, status;
    struct tec_unit *units, *unitpgn;
    const char *errfmt = "cannot show env units '%s': %s";

    retcode = LIBTEC_OK;
    units = unitpgn = NULL;
    opt_quiet = opt_help = false;
    args.env = args.desk = args.taskid = NULL;
    while ((c = getopt(argc, argv, ":hq")) != -1) {
        switch (c) {
        case 'h':
            opt_help = true;
            break;
        case 'q':
            opt_quiet = true;
            break;
        case ':':
            return elog(1, "option `-%c' requires an argument", optopt);
        default:
            return elog(1, "invalid option `-%c'", optopt);
        }
    }
    i = optind;

    if (opt_help)
        return help_usage("desk-cat");

    if ((status = check_arg_env(&args, errfmt, opt_quiet)))
        return status;

    do {
        args.desk = argv[i];
        if ((status = check_arg_desk(&args, errfmt, opt_quiet))) {
            ;
        } else if ((status = tec_desk_get(teccfg.base.task, &args, ctx))) {
            if (opt_quiet == false)
                elog(status, errfmt, argv[i], tec_strerror(status));
            ;
        } else {
            printf("%-7s : %s\n", "desk", args.desk);
            for (units = ctx->units; units; units = units->next)
                printf("%-7s : %s\n", units->key, units->val);

            // TODO: add plugin output
        }

        unitpgn = tec_unit_free(unitpgn);
        ctx->units = tec_unit_free(ctx->units);
        retcode = status == LIBTEC_OK ? retcode : status;
    } while (++i < argc);
    return retcode;
}

static int _desk_cd(int argc, char **argv, tec_ctx_t *ctx)
{
    tec_arg_t args;
    int c, i, retcode, status;
    char alias[DESKSIZ + 1] = { 0 };
    const char *errfmt = "cannot switch to '%s': %s";
    int opt_cd_dir, opt_cd_toggle, opt_help, opt_quiet;

    retcode = LIBTEC_OK;
    opt_quiet = opt_help = false;
    opt_cd_toggle = opt_cd_dir = true;
    args.env = args.desk = args.taskid = NULL;
    while ((c = getopt(argc, argv, ":e:hnqN")) != -1) {
        switch (c) {
        case 'h':
            opt_help = true;
            break;
        case 'n':
            opt_cd_toggle = false;
            break;
        case 'e':
            args.env = optarg;
            break;
        case 'q':
            opt_quiet = true;
            break;
        case 'N':
            opt_cd_dir = false;
            opt_cd_toggle = false;
            break;
        case ':':
            return elog(1, "option `-%c' requires an argument", optopt);
        default:
            return elog(1, "invalid option `-%c'", optopt);
        }
    }

    i = optind;

    if (opt_help == true)
        return help_usage("desk-cd");

    if ((status = check_arg_env(&args, errfmt, opt_quiet)))
        return status;

    /* Check that alias '-' is not passed with other desks nor duplicated.  */
    for (int idx = i; idx < argc; ++idx) {
        if (strcmp(argv[idx], "-") == 0 && argc > 2)
            return elog(1, "alias '-' is used alone");
    }

    /* Resolve alias '-' to switch to previous environment.  */
    if (argv[i] && strcmp("-", argv[i]) == 0) {
        if ((status = toggle_desk_get_prev(teccfg.base.task, &args)))
            return elog(1, errfmt, "PREV", "no previous desk");
        argv[i] = strncpy(alias, args.desk, DESKSIZ);
    }

    do {
        args.desk = argv[i];

        if ((status = check_arg_desk(&args, errfmt, opt_quiet))) {
            ;
        } else if ((status = hook_action(&args, "desk-cd"))) {
            if (opt_quiet == false)
                elog(status, errfmt, args.taskid, "failed to execute hooks");
        } else if (opt_cd_toggle == true) {
            if ((status = toggle_desk_set_curr(teccfg.base.task, &args))) {
                if (opt_quiet == false)
                    elog(1, "could not update toggles");
            }
        }
        retcode = status == LIBTEC_OK ? retcode : status;
    } while (++i < argc);

    return retcode == LIBTEC_OK && opt_cd_dir ? tec_pwd_desk(&args) : retcode;
}

static const builtin_t desk_commands[] = {
    {.name = "add",.func = &_desk_add},
    {.name = "cat",.func = &_desk_cat},
    {.name = "cd",.func = &_desk_cd},
    {.name = "ls",.func = &_desk_ls},
    {.name = "mv",.func = &_desk_mv},
    {.name = "rm",.func = &_desk_rm},
    {.name = "set",.func = &_desk_set},
};

int tec_cli_desk(int argc, char **argv, tec_ctx_t *ctx)
{
    char *cmd = argv[1] != NULL ? argv[1] : "ls";

    for (int i = 0; i < ARRAY_SIZE(desk_commands); ++i)
        if (strcmp(cmd, desk_commands[i].name) == 0)
            return desk_commands[i].func(argc - 1, argv + 1, ctx);

    return elog(1, "'%s': no such desk subcommand", cmd);
}
