#include <ctype.h>
#include <string.h>
#include <dirent.h>

#include "tec.h"
#include "aux/config.h"
#include "aux/toggle.h"

static int get_user_choice(void)
{
    char choice[10] = { 0 };

    fgets(choice, sizeof(choice), stdin);
    if (choice[0] == 'y' || choice[0] == 'Y')
        return 1;
    return 0;
}

static int generate_units(tec_ctx_t *ctx, char *env)
{
    struct tec_unit *units = NULL;
    char desc[100] = "autogenerated desciption for environment ";

    strcat(desc, env);
    units = tec_unit_add(units, "desc", desc);
    ctx->units = units;
    return 0;
}

static int valid_desc(const char *val)
{
    if (!isalnum(*val++))
        return false;
    for (; *val; ++val)
        if (!(isalnum(*val) || isspace(*val) || *val == '_' || *val == '-'))
            return false;
    return isalnum(*--val) != 0;
}

// TODO: Find a good error message in case option fails.  */
static int _env_add(int argc, char **argv, tec_ctx_t *ctx)
{
    char c;
    tec_arg_t args;
    int switch_dir, switch_env;
    int i, quiet, showhelp, status;
    const char *errfmt = "cannot add env '%s': %s";
    const char *errfmt_desk = "cannot add desk '%s': %s";

    status = LIBTEC_OK;
    showhelp = quiet = false;
    switch_dir = switch_env = true;
    args.env = args.desk = args.taskid = NULL;
    while ((c = getopt(argc, argv, ":d:hnqN")) != -1) {
        switch (c) {
        case 'd':
            args.desk = optarg;
            break;
        case 'h':
            showhelp = true;
            break;
        case 'n':
            switch_env = false;
            break;
        case 'q':
            quiet = true;
            break;
        case 'N':
            switch_dir = false;
            switch_env = false;
            break;
        case ':':
            return elog(1, "option `-%c' requires an argument", optopt);
        default:
            return elog(1, "invalid option `-%c'", optopt);
        }
    }

    if (showhelp)
        return help_usage("env-add");

    if (optind == argc)
        return elog(1, "env name required");
    else if ((ctx->column = generate_column("todo")) == NULL) {
        if (quiet == false)
            elog(1, "could not generate column");
        return 1;
    }

    /* Set default desk name to create.  */
    if (args.desk == NULL)
        args.desk = "desk";

    for (i = optind; i < argc; ++i) {
        args.env = argv[i];

        if (is_valid_length(args.env, ENVSIZ) == false) {
            if (quiet == false)
                elog(status, errfmt, args.env, "env name is too long");
            continue;
        } else if ((status = tec_env_valid(teccfg.base.task, &args))) {
            if (quiet == false)
                elog(status, errfmt, args.env, tec_strerror(status));
            continue;
        } else if (!(status = tec_env_exist(teccfg.base.task, &args))) {
            char *env = args.env;
            if (quiet == false)
                elog(status, errfmt, env, tec_strerror(LIBTEC_ARG_EXISTS));
            continue;
        }

        if ((status = tec_desk_valid(teccfg.base.task, &args))) {
            if (quiet == false)
                elog(status, errfmt_desk, args.desk, tec_strerror(status));
            continue;
        } else if (is_valid_length(args.desk, DESKSIZ) == false) {
            if (quiet == false)
                elog(status, errfmt_desk, args.desk, "desk name is too long");
            continue;
        } else if (!(status = tec_desk_exist(teccfg.base.task, &args))) {
            if (quiet == false)
                elog(status, errfmt_desk, args.desk,
                     tec_strerror(LIBTEC_ARG_EXISTS));
            continue;
        }

        if (generate_units(ctx, args.env)) {
            if (quiet == false)
                elog(1, errfmt, args.env, "unit generation failed");
            continue;
        }

        if ((status = tec_env_add(teccfg.base.task, &args, ctx))) {
            if (quiet == false)
                elog(1, errfmt, argv[i], tec_strerror(status));
            continue;
        } else if ((status = tec_desk_add(teccfg.base.task, &args, ctx))) {
            if (quiet == false)
                elog(1, errfmt, argv[i], tec_strerror(status));
            continue;
        }
        ctx->units = tec_unit_free(ctx->units);
    }

    ctx->column = tec_unit_free(ctx->column);

    if ((switch_env && status == LIBTEC_OK)
        && toggle_env_set_curr(teccfg.base.task, &args)) {
        if (quiet == false)
            elog(status, "could not update env toggles");
        return 1;
    } else if ((switch_env && status == LIBTEC_OK)
               && toggle_desk_set_curr(teccfg.base.task, &args)) {
        if (quiet == false)
            elog(status, "could not update desk toggles");
        return 1;
    }

    return (switch_dir && status == LIBTEC_OK) ? tec_pwd_env(&args) : status;
}

static int _env_rm(int argc, char **argv, tec_ctx_t *ctx)
{
    tec_arg_t args;
    int i, c, retcode, status;
    const char *errfmt = "cannot delete env: %s";
    int opt_ask_once, opt_ask_every, opt_quiet, opt_help, opt_verbose;

    retcode = LIBTEC_OK;
    opt_quiet = opt_help = opt_verbose = false;
    args.env = args.desk = args.taskid = NULL;
    while ((c = getopt(argc, argv, ":d:fhiqvI")) != -1) {
        switch (c) {
        case 'd':
            args.desk = optarg;
            break;
        case 'f':
            opt_ask_every = false;
            opt_ask_once = false;
            break;
        case 'h':
            opt_help = true;
            break;
        case 'i':
            opt_ask_every = true;
            opt_ask_once = false;
            break;
        case 'q':
            opt_quiet = true;
            break;
        case 'v':
            opt_verbose = true;
            break;
        case 'I':
            opt_ask_every = false;
            opt_ask_once = true;
            break;
        case ':':
            return elog(1, "option `-%c' requires an argument", optopt);
        default:
            return elog(1, "invalid option `-%c'", optopt);
        }
    }
    i = optind;

    if (opt_help)
        return help_usage("env-rm");

    if (opt_ask_once == true) {
        printf("Are you sure to remove environment(s)? [y/N] ");
        if (get_user_choice() == false) {
            return LIBTEC_OK;
        }
    }

    do {
        args.env = argv[i];
        if ((status = check_arg_env(&args, errfmt, opt_quiet))) {
            retcode = status == LIBTEC_OK ? retcode : status;
            continue;
        } else if (opt_ask_every == true) {
            printf("Are you sure to remove environment '%s'? [y/N] ", args.env);
            if (get_user_choice() != true) {
                continue;
            }
        }

        if ((status = hook_action(&args, "env-rm"))) {
            if (opt_quiet == false)
                elog(1, errfmt, args.taskid, "failed to execute hooks");
        } else if ((status = tec_env_del(teccfg.base.task, &args, ctx))) {
            if (opt_quiet == false)
                elog(status, errfmt, argv[i], tec_strerror(status));
        }

        if (opt_verbose == true)
            llog(0, "removed environment '%s'", args.env);
        retcode = status == LIBTEC_OK ? retcode : status;
    } while (++i < argc);

    // TODO: update current directory if current env got deleted.
    return retcode == LIBTEC_OK ? tec_pwd_env(&args) : retcode;
}

static int _env_ls(int argc, char **argv, tec_ctx_t *ctx)
{
    int c, status;
    tec_arg_t args;
    int opt_help, opt_quiet;

    opt_quiet = false;
    opt_help = false;
    args.env = args.desk = args.taskid = NULL;
    while ((c = getopt(argc, argv, ":hq")) != -1) {
        switch (c) {
        case 'q':
            opt_quiet = true;
            break;
        case 'h':
            opt_help = true;
            break;
        case ':':
            return elog(1, "option `-%c' requires an argument", optopt);
        default:
            return elog(1, "invalid option `-%c'", optopt);
        }
    }

    if (opt_help == true)
        return help_usage("env-ls");

    if ((status = tec_env_list(teccfg.base.task, &args, ctx))) {
        if (opt_quiet == false) {
            const char *errfmt = "cannot list env(s) '%s': %s";
            elog(status, errfmt, "ENV", tec_strerror(status));
            return status;
        }
    }

    for (tec_list_t * obj = ctx->list; obj != NULL; obj = obj->next) {
        LIST_OBJ_UNITS("mark", obj->name, "", "some env description");
    }
    ctx->list = tec_list_free(ctx->list);
    return status;
}

static int _env_rename(int argc, char **argv, tec_ctx_t *ctx)
{
    char *errfmt;
    tec_arg_t src, dst;
    int status;
    int c, opt_quiet, opt_help;

    opt_quiet = opt_help = false;
    errfmt = "could not rename env: %s";
    src.env = src.desk = src.taskid = NULL;
    dst.env = dst.desk = dst.taskid = NULL;
    while ((c = getopt(argc, argv, ":hq")) != -1) {
        switch (c) {
        case 'h':
            opt_help = true;
            break;
        case 'q':
            opt_quiet = true;
            break;
        default:
            return elog(1, "invalid option `-%c'", optopt);
        }
    }

    if (opt_help)
        return help_usage("env-rename");

    if (argc - optind != 2)
        return elog(1, "source or destination env name missing");

    src.env = argv[optind];
    dst.env = argv[optind + 1];

    /* TODO: trigger hooks if any */

    if ((status = check_arg_env(&src, errfmt, opt_quiet)))
        return status;
    else if ((status = check_arg_env(&src, errfmt, opt_quiet)))
        return status;
    else if (tec_env_exist(teccfg.base.task, &dst)) {
        if (opt_quiet == false)
            elog(1, "'%s': destination env exists\n", dst.env);
        return status;
    }

    if ((status = tec_env_rename(teccfg.base.task, &src, &dst, NULL))) {
        if (opt_quiet == false)
            elog(status, errfmt, tec_strerror(status));
        return status;
    }
    return tec_pwd_env(&dst);
}

static int _env_set(int argc, char **argv, tec_ctx_t *ctx)
{
    tec_arg_t args;
    int atleast_one_key_set;
    int c, i, retcode, status;
    int opt_quiet, opt_help;
    const char *errfmt = "could not set env unit value '%s': %s";

    retcode = LIBTEC_OK;
    opt_quiet = opt_help = false;
    atleast_one_key_set = false;
    args.env = args.desk = args.taskid = NULL;
    while ((c = getopt(argc, argv, ":d:hqD:")) != -1) {
        switch (c) {
        case 'd':
            args.desk = optarg;
            break;
        case 'h':
            opt_help = true;
            break;
        case 'q':
            opt_quiet = true;
            break;
        case 'D':
            if (valid_desc(optarg) == false) {
                elog(1, "invalid description '%s'", optarg);
                help_usage("env-set");
                return 1;
            }
            atleast_one_key_set = true;
            ctx->units = tec_unit_add(ctx->units, "desc", optarg);
            break;
        case ':':
            return elog(1, "option `-%c' requires an argument", optopt);
        default:
            return elog(1, "invalid option `-%c'", optopt);
        }
    }

    if (opt_help)
        return help_usage("env-set");
    else if (atleast_one_key_set == false) {
        elog(1, "gotta supply one of the options");
        help_usage("env-set");
        return 1;
    }

    i = optind;
    do {
        args.env = argv[i];

        if ((status = check_arg_env(&args, errfmt, opt_quiet))) {
            ;
        } else if ((status = tec_env_set(teccfg.base.task, &args, ctx))) {
            if (opt_quiet == false)
                elog(status, errfmt, argv[i], tec_strerror(status));
        } else if ((status = hook_action(&args, "env-set"))) {
            if (opt_quiet == false)
                elog(status, errfmt, args.taskid, "failed to execute hooks");
        }
        retcode = status == LIBTEC_OK ? retcode : status;
    } while (++i < argc);

    ctx->units = tec_unit_free(ctx->units);
    return status;
}

static int _env_cat(int argc, char **argv, tec_ctx_t *ctx)
{
    tec_arg_t args;
    int c, i, quiet, showhelp, status;
    struct tec_unit *unitbin, *unitpgn;
    const char *errfmt = "cannot show env units '%s': %s";

    unitbin = unitpgn = NULL;
    quiet = showhelp = false;
    args.env = args.desk = args.taskid = NULL;
    while ((c = getopt(argc, argv, ":d:hq")) != -1) {
        switch (c) {
        case 'd':
            args.desk = optarg;
            break;
        case 'h':
            showhelp = true;
            break;
        case 'q':
            quiet = true;
            break;
        case ':':
            return elog(1, "option `-%c' requires an argument", optopt);
        default:
            return elog(1, "invalid option `-%c'", optopt);
        }
    }

    if (showhelp)
        return help_usage("env-cat");

    i = optind;
    do {
        args.env = argv[i];
        if ((status = check_arg_env(&args, errfmt, quiet))) {
            continue;
        } else if ((status = tec_env_get(teccfg.base.task, &args, ctx))) {
            if (quiet == false)
                elog(status, errfmt, argv[i], tec_strerror(status));
            continue;
        }

        printf("%-7s : %s\n", "env", args.env);
        for (unitbin = ctx->units; unitbin; unitbin = unitbin->next)
            printf("%-7s : %s\n", unitbin->key, unitbin->val);

        // TODO: add plugin output
    } while (++i < argc);

    return status;
}

static int _env_cd(int argc, char **argv, tec_ctx_t *ctx)
{
    tec_arg_t args;
    int c, i, retcode, status;
    char alias[ENVSIZ + 1] = { 0 };
    const char *errfmt = "cannot switch to '%s': %s";
    int opt_quiet, opt_help, opt_cd_toggle, opt_cd_dir;

    retcode = LIBTEC_OK;
    opt_quiet = opt_help = false;
    opt_cd_toggle = opt_cd_dir = true;
    args.env = args.desk = args.taskid = NULL;
    while ((c = getopt(argc, argv, ":d:hnqN")) != -1) {
        switch (c) {
        case 'd':
            args.desk = optarg;
            break;
        case 'h':
            opt_help = true;
            break;
        case 'n':
            opt_cd_toggle = false;
            break;
        case 'q':
            opt_quiet = true;
            break;
        case 'N':
            opt_cd_dir = false;
            opt_cd_toggle = false;
            break;
        case ':':
            return elog(1, "option `-%c' requires an argument", optopt);
        default:
            return elog(1, "invalid option `-%c'", optopt);
        }
    }

    i = optind;

    if (opt_help == true)
        return help_usage("env-cd");

    /* Check that alias '-' is not passed with other envs nor duplicated.  */
    for (int idx = i; idx < argc; ++idx) {
        if (strcmp(argv[idx], "-") == 0 && argc > 2)
            return elog(1, "alias '-' is used alone");
    }

    /* Resolve alias '-' to switch to previous environment.  */
    if (argv[i] && strcmp("-", argv[i]) == 0) {
        if ((status = toggle_env_get_prev(teccfg.base.task, &args)))
            return elog(1, errfmt, "PREV", "no previous environment");
        argv[i] = strncpy(alias, args.env, ENVSIZ);
    }

    do {
        args.env = argv[i];
        if ((status = check_arg_env(&args, errfmt, opt_quiet))) {
            ;
        } else if ((status = hook_action(&args, "env-cd"))) {
            if (opt_quiet == false)
                elog(status, errfmt, args.taskid, "failed to execute hooks");
        } else if (opt_cd_toggle == true) {
            if ((status = toggle_env_set_curr(teccfg.base.task, &args))) {
                if (opt_quiet == false)
                    elog(1, "could not update toggles");
            }
        }
        retcode = status == LIBTEC_OK ? retcode : status;
    } while (++i < argc);

    return retcode == LIBTEC_OK && opt_cd_dir ? tec_pwd_env(&args) : retcode;
}

static const builtin_t env_commands[] = {
    {.name = "add",.func = &_env_add},
    {.name = "cat",.func = &_env_cat},
    {.name = "cd",.func = &_env_cd},
    {.name = "ls",.func = &_env_ls},
    {.name = "rename",.func = &_env_rename},
    {.name = "rm",.func = &_env_rm},
    {.name = "set",.func = &_env_set},
};

int tec_cli_env(int argc, char **argv, tec_ctx_t *ctx)
{
    char *cmd = argv[1] != NULL ? argv[1] : "ls";

    for (int i = 0; i < ARRAY_SIZE(env_commands); ++i)
        if (strcmp(cmd, env_commands[i].name) == 0)
            return env_commands[i].func(argc - 1, argv + 1, ctx);

    return elog(1, "'%s': no such env command", cmd);
}
