#include <ctype.h>
#include <string.h>
#include <dirent.h>

#include "tec.h"
#include "aux/config.h"
#include "aux/toggle.h"

static int generate_units(tec_ctx_t *ctx, char *env)
{
    struct tec_unit *units = NULL;
    char desc[100] = "autogenerated desciption for environment ";

    strcat(desc, env);
    units = tec_unit_add(units, "desc", desc);
    ctx->units = units;
    return 0;
}

static int valid_desc(const char *val)
{
    if (!isalnum(*val++))
        return false;
    for (; *val; ++val)
        if (!(isalnum(*val) || isspace(*val) || *val == '_' || *val == '-'))
            return false;
    return isalnum(*--val) != 0;
}

// TODO: Find a good error message in case option fails.  */
static int _env_add(int argc, char **argv, tec_ctx_t *ctx)
{
    char c;
    tec_arg_t args;
    int switch_dir, switch_env;
    int i, quiet, showhelp, status;
    const char *errfmt = "cannot add env '%s': %s";
    const char *errfmt_desk = "cannot add desk '%s': %s";

    status = LIBTEC_OK;
    showhelp = quiet = false;
    switch_dir = switch_env = true;
    args.env = args.desk = args.taskid = NULL;
    while ((c = getopt(argc, argv, ":d:hnqN")) != -1) {
        switch (c) {
        case 'd':
            args.desk = optarg;
            break;
        case 'h':
            showhelp = true;
            break;
        case 'n':
            switch_env = false;
            break;
        case 'q':
            quiet = true;
            break;
        case 'N':
            switch_dir = false;
            switch_env = false;
            break;
        case ':':
            return elog(1, "option `-%c' requires an argument", optopt);
        default:
            return elog(1, "invalid option `-%c'", optopt);
        }
    }

    if (showhelp)
        return help_usage("env-add");

    if (optind == argc)
        return elog(1, "env name required");
    else if ((ctx->column = generate_column("todo")) == NULL) {
        if (quiet == false)
            elog(1, "could not generate column");
        return 1;
    }

    /* Set default desk name to create.  */
    if (args.desk == NULL)
        args.desk = "desk";

    for (i = optind; i < argc; ++i) {
        args.env = argv[i];

        if (is_valid_length(args.env, PRJSIZ) == false) {
            if (quiet == false)
                elog(status, errfmt, args.env, "env name is too long");
            continue;
        } else if ((status = tec_env_valid(teccfg.base.task, &args))) {
            if (quiet == false)
                elog(status, errfmt, args.env, tec_strerror(status));
            continue;
        } else if (!(status = tec_env_exist(teccfg.base.task, &args))) {
            char *env = args.env;
            if (quiet == false)
                elog(status, errfmt, env, tec_strerror(LIBTEC_ARG_EXISTS));
            continue;
        }

        if ((status = tec_desk_valid(teccfg.base.task, &args))) {
            if (quiet == false)
                elog(status, errfmt_desk, args.desk, tec_strerror(status));
            continue;
        } else if (is_valid_length(args.desk, BRDSIZ) == false) {
            if (quiet == false)
                elog(status, errfmt_desk, args.desk, "desk name is too long");
            continue;
        } else if (!(status = tec_desk_exist(teccfg.base.task, &args))) {
            if (quiet == false)
                elog(status, errfmt_desk, args.desk,
                     tec_strerror(LIBTEC_ARG_EXISTS));
            continue;
        }

        if (generate_units(ctx, args.env)) {
            if (quiet == false)
                elog(1, errfmt, args.env, "unit generation failed");
            continue;
        }

        if ((status = tec_env_add(teccfg.base.task, &args, ctx))) {
            if (quiet == false)
                elog(1, errfmt, argv[i], tec_strerror(status));
            continue;
        } else if ((status = tec_desk_add(teccfg.base.task, &args, ctx))) {
            if (quiet == false)
                elog(1, errfmt, argv[i], tec_strerror(status));
            continue;
        }
        ctx->units = tec_unit_free(ctx->units);
    }

    ctx->column = tec_unit_free(ctx->column);

    if ((switch_env && status == LIBTEC_OK)
        && toggle_env_set_curr(teccfg.base.task, &args)) {
        if (quiet == false)
            elog(status, "could not update env toggles");
        return 1;
    } else if ((switch_env && status == LIBTEC_OK)
               && toggle_desk_set_curr(teccfg.base.task, &args)) {
        if (quiet == false)
            elog(status, "could not update desk toggles");
        return 1;
    }

    return (switch_dir && status == LIBTEC_OK) ? tec_pwd_env(&args) : status;
}

static int _env_rm(int argc, char **argv, tec_ctx_t *ctx)
{
    char c;
    tec_arg_t args;
    const char *errfmt = "cannot delete env: %s";
    int i, choice, quiet, showhelp, showprompt, status;

    showprompt = true;
    choice = quiet = showhelp = false;
    args.env = args.desk = args.taskid = NULL;
    while ((c = getopt(argc, argv, ":d:hnq")) != -1) {
        switch (c) {
        case 'd':
            args.desk = optarg;
            break;
        case 'h':
            showhelp = true;
            break;
        case 'n':
            showprompt = false;
            break;
        case 'q':
            quiet = true;
            break;
        case ':':
            return elog(1, "option `-%c' requires an argument", optopt);
        default:
            return elog(1, "invalid option `-%c'", optopt);
        }
    }

    if (showhelp)
        return help_usage("env-rm");

    if (showprompt) {
        printf("Are you sure to delete env(s)? [y/N] ");
        choice = getchar();
        if (choice != 'y' && choice != 'Y') {
            return 0;
        }
    }

    i = optind;
    do {
        args.env = argv[i];
        if ((status = tec_env_del(teccfg.base.task, &args, ctx)) != LIBTEC_OK) {
            if (quiet == false)
                elog(status, errfmt, argv[i], tec_strerror(status));
        }
    } while (++i < argc);

    // TODO: update current directory if current env got deleted.
    return status == LIBTEC_OK ? tec_pwd_env(&args) : status;
}

static int _env_ls(int argc, char **argv, tec_ctx_t *ctx)
{
    int c, quiet, status;
    tec_arg_t args;
    int opt_help;

    quiet = false;
    opt_help = false;
    args.env = args.desk = args.taskid = NULL;
    while ((c = getopt(argc, argv, ":hq")) != -1) {
        switch (c) {
        case 'q':
            quiet = true;
            break;
        case 'h':
            opt_help = true;
            break;
        case ':':
            return elog(1, "option `-%c' requires an argument", optopt);
        default:
            return elog(1, "invalid option `-%c'", optopt);
        }
    }

    if (opt_help == true)
        return help_usage("env-ls");

    if ((status = tec_env_list(teccfg.base.task, &args, ctx))) {
        if (quiet == false) {
            const char *errfmt = "cannot list env(s) '%s': %s";
            elog(status, errfmt, "ENV", tec_strerror(status));
            return status;
        }
    }

    for (tec_list_t * obj = ctx->list; obj != NULL; obj = obj->next) {
        LIST_OBJ_UNITS("mark", obj->name, "", "some env description");
    }
    ctx->list = tec_list_free(ctx->list);
    return status;
}

static int _env_prev(int argc, char **argv, tec_ctx_t *ctx)
{
    tec_arg_t args;
    char c, *errfmt;
    int quiet, showhelp, status;

    quiet = showhelp = false;
    args.env = args.desk = args.taskid = NULL;
    errfmt = "cannot switch to previous env '%s': %s";
    while ((c = getopt(argc, argv, ":hq")) != -1) {
        switch (c) {
        case 'h':
            showhelp = true;
            break;
        case 'q':
            quiet = true;
            break;
        case ':':
            return elog(1, "option `-%c' requires an argument", optopt);
        default:
            return elog(1, "invalid option `-%c'", optopt);
        }
    }

    if (showhelp == true)
        return help_usage("env-prev");

    if ((status = toggle_env_get_prev(teccfg.base.task, &args))) {
        if (quiet == false)
            elog(status, errfmt, "NOPREV", "no previous env");
        return status;
    } else if ((status = toggle_env_get_curr(teccfg.base.task, &args))) {
        if (quiet == false)
            elog(status, errfmt, "NOCURR", "no current env");
        return status;
    }

    if (toggle_env_swap(teccfg.base.task, &args)) {
        if (quiet == false)
            elog(1, "could not update toggle");
        return 1;
    }

    return status == LIBTEC_OK ? tec_pwd_env(&args) : status;
}

static int _env_rename(int argc, char **argv, tec_ctx_t *ctx)
{
    char *errfmt;
    tec_arg_t src, dst;
    int c, quiet, showhelp, status;

    quiet = showhelp = false;
    errfmt = "could not rename env: %s";
    src.env = src.desk = src.taskid = NULL;
    dst.env = dst.desk = dst.taskid = NULL;
    while ((c = getopt(argc, argv, ":hq")) != -1) {
        switch (c) {
        case 'h':
            showhelp = true;
            break;
        case 'q':
            quiet = true;
            break;
        default:
            return elog(1, "invalid option `-%c'", optopt);
        }
    }

    if (showhelp)
        return help_usage("env-rename");

    if (argc - optind != 2)
        return elog(1, "source or destination env name missing");

    src.env = argv[optind];
    dst.env = argv[optind + 1];

    /* TODO: trigger hooks if any */

    if ((status = check_arg_env(&src, errfmt, quiet)))
        return status;
    else if ((status = check_arg_env(&src, errfmt, quiet)))
        return status;
    else if (tec_env_exist(teccfg.base.task, &dst)) {
        if (quiet == false)
            elog(1, "'%s': destination env exists\n", dst.env);
        return status;
    }

    if ((status = tec_env_rename(teccfg.base.task, &src, &dst, NULL))) {
        if (quiet == false)
            elog(status, errfmt, tec_strerror(status));
        return status;
    }
    return tec_pwd_env(&dst);
}

static int _env_set(int argc, char **argv, tec_ctx_t *ctx)
{
    tec_arg_t args;
    int atleast_one_key_set;
    int c, i, quiet, showhelp;
    const char *errfmt = "could not set env unit value '%s': %s";

    quiet = showhelp = false;
    atleast_one_key_set = false;
    args.env = args.desk = args.taskid = NULL;
    while ((c = getopt(argc, argv, ":d:hqD:")) != -1) {
        switch (c) {
        case 'd':
            args.desk = optarg;
            break;
        case 'h':
            showhelp = true;
            break;
        case 'q':
            quiet = true;
            break;
        case 'D':
            if (valid_desc(optarg) == false) {
                elog(1, "invalid description '%s'", optarg);
                help_usage("env-set");
                return 1;
            }
            atleast_one_key_set = true;
            ctx->units = tec_unit_add(ctx->units, "desc", optarg);
            break;
        case ':':
            return elog(1, "option `-%c' requires an argument", optopt);
        default:
            return elog(1, "invalid option `-%c'", optopt);
        }
    }

    if (showhelp)
        return help_usage("env-set");
    if (atleast_one_key_set == false) {
        elog(1, "gotta supply one of the options");
        help_usage("env-set");
        return 1;
    }

    i = optind;
    do {
        int status;
        args.env = argv[i];

        if ((status = tec_env_set(teccfg.base.task, &args, ctx))) {
            if (quiet == false)
                elog(status, errfmt, argv[i], tec_strerror(status));
        }
    } while (++i < argc);

    ctx->units = tec_unit_free(ctx->units);
    return 0;
}

// roach: maybe it'll be useful
static int _env_cat(int argc, char **argv, tec_ctx_t *ctx)
{
    tec_arg_t args;
    int c, i, quiet, showhelp, status;
    struct tec_unit *unitbin, *unitpgn;
    const char *errfmt = "cannot show env units '%s': %s";

    unitbin = unitpgn = NULL;
    quiet = showhelp = false;
    args.env = args.desk = args.taskid = NULL;
    while ((c = getopt(argc, argv, ":d:hq")) != -1) {
        switch (c) {
        case 'd':
            args.desk = optarg;
            break;
        case 'h':
            showhelp = true;
            break;
        case 'q':
            quiet = true;
            break;
        case ':':
            return elog(1, "option `-%c' requires an argument", optopt);
        default:
            return elog(1, "invalid option `-%c'", optopt);
        }
    }

    if (showhelp)
        return help_usage("env-cat");

    i = optind;
    do {
        args.env = argv[i];
        if ((status = tec_env_get(teccfg.base.task, &args, ctx))) {
            if (quiet == false)
                elog(status, errfmt, argv[i], tec_strerror(status));
            continue;
        }

        printf("%-7s : %s\n", "env", args.env);
        for (unitbin = ctx->units; unitbin; unitbin = unitbin->next)
            printf("%-7s : %s\n", unitbin->key, unitbin->val);

        // TODO: add plugin output
    } while (++i < argc);

    return status;
}

static int _env_cd(int argc, char **argv, tec_ctx_t *ctx)
{
    tec_arg_t args;
    int c, i, quiet, showhelp, status;
    const char *errfmt = "cannot switch to '%s': %s";
    int switch_toggle, switch_dir;

    quiet = showhelp = false;
    switch_toggle = switch_dir = true;
    args.env = args.desk = args.taskid = NULL;
    while ((c = getopt(argc, argv, ":d:hnqN")) != -1) {
        switch (c) {
        case 'd':
            args.desk = optarg;
            break;
        case 'h':
            showhelp = true;
            break;
        case 'n':
            switch_toggle = false;
            break;
        case 'q':
            quiet = true;
            break;
        case 'N':
            switch_dir = false;
            switch_toggle = false;
            break;
        case ':':
            return elog(1, "option `-%c' requires an argument", optopt);
        default:
            return elog(1, "invalid option `-%c'", optopt);
        }
    }

    if (showhelp)
        return help_usage("env-cd");

    i = optind;

    /* Alias to switch to previous environment.  */
    if (argv[i] && strcmp("-", argv[i]) == 0) {
        argv[i] = NULL;         /* NULL it cuz it's an alias and illegal environment name.  */
        switch_toggle = true;
        if ((status = toggle_env_get_prev(teccfg.base.task, &args)))
            return elog(1, errfmt, "PREV",
                        "could not get previous environment");
    }

    do {
        args.env = args.env != NULL ? args.env : argv[i];

        if ((status = check_arg_env(&args, errfmt, quiet)))
            continue;
    } while (++i < argc);

    if (status == LIBTEC_OK && switch_toggle == true) {
        if (toggle_env_set_curr(teccfg.base.task, &args)
            && quiet == false)
            status = elog(1, "could not update env toggles");
    }

    return status == LIBTEC_OK && switch_dir ? tec_pwd_env(&args) : status;
}

static const builtin_t env_commands[] = {
    {.name = "add",.func = &_env_add},
    {.name = "cat",.func = &_env_cat},
    {.name = "cd",.func = &_env_cd},
    {.name = "ls",.func = &_env_ls},
    {.name = "prev",.func = &_env_prev},
    {.name = "rename",.func = &_env_rename},
    {.name = "rm",.func = &_env_rm},
    {.name = "set",.func = &_env_set},
};

int tec_cli_env(int argc, char **argv, tec_ctx_t *ctx)
{
    char *cmd = argv[1] != NULL ? argv[1] : "ls";

    for (int i = 0; i < ARRAY_SIZE(env_commands); ++i)
        if (strcmp(cmd, env_commands[i].name) == 0)
            return env_commands[i].func(argc - 1, argv + 1, ctx);

    return elog(1, "'%s': no such env command", cmd);
}
