#include <stdio.h>
#include <string.h>

#include "tec.h"

#define PADDING     "    "
#define SYSTEM      "system"
#define TAGOBJ      "bin-object"
#define TAGOBJCMD   "bin-object-cmd"
#define TAGSYSTEM   "bin-system"
#define TAGBASIC    "bin-basic"

struct help {
    const char *tag;
    const char *name;
    const char *synop;
    const char *desc_short;
    const char *desc_long;
};

struct helpctx {
    int synop;
    int desc_short;
    int desc_long;
};

struct helpctx helpctx = {
    .synop = false,
    .desc_short = false,
    .desc_long = false,
};

struct help helptab[] = {
    {
     .tag = SYSTEM,
     .name = "tec",
     .synop = "Usage: " PROGRAM " [OPTION]... COMMAND|PLUGIN\n",
     .desc_short = "Terminal environment and task manager.\n",
     .desc_long = "\n\
    Options:\n\
      -h      show this help and exit\n\
      -C TOG  enbale colors (default: disabled)\n\
      -D TOG  enbale debug mode (default: disabled)\n\
      -F DIR  path to the config file (under development)\n\
      -H TOG  enbale hooks (default: disabled)\n\
      -P DIR  directory where plugins are stored\n\
      -T DIR  directory where tasks are stored\n\
      -V      show version and exit\n\
    \n\
    Arguments:\n\
      DIR     path to directory\n\
      TOG     can be either 'on' or 'off'\n\
    \n\
    Notes:\n\
    It's more convient to set options in config file. This way no need\n\
    to type them every time.\n\
    \n\
    Exit status:\n\
    Return status of builtin command or plugin\n"},
    {
     .tag = TAGSYSTEM,
     .name = "help",
     .synop = "Usage: " PROGRAM " help [OPTION]... [CMD]\n",
     .desc_short = "Show help for commands.\n",
     .desc_long = "\n\
    If no CMD passed, list all commands with short description.\n\
    \n\
    Options:\n\
      -d      output short description for each topic\n\
      -s      output only a short usage synopsis for each topic matching\n\
    \n\
    Arguments:\n\
      CMD     builtin command\n\
    \n\
    Exit status:\n\
    Returns success unless PATTERN is not found or an invalid option is given.\n"},
    {
     .tag = TAGSYSTEM,
     .name = "init",
     .synop = "Usage: " PROGRAM " init\n",
     .desc_short = "Init directory structure.\n",
     .desc_long = "\n\
    Exit status:\n\
    Under development\n"},

    {
     .tag = TAGBASIC,
     .name = "add",
     .synop = "Usage: " PROGRAM " add [OPTION]... [ID]...\n",
     .desc_short = "Add a new task to environment.\n",
     .desc_long = "\n\
    Options:\n\
      -d DESK desk name (default is current)\n\
      -e ENV  environment name (default is current)\n\
      -h      show this help and exit\n\
      -n      do not switch to task\n\
      -q      do not write anything to standard error output\n\
      -N      neither switch to task nor to task directory\n\
    \n\
    Arguments:\n\
      DESK    desk name (default is current)\n\
      ID      task ID, if none passed then generated by util\n\
      ENV     environment name (default is current)\n\
    \n\
    Exit status:\n\
    Under development\n"},
    {
     .tag = TAGBASIC,
     .name = "cat",
     .synop = "Usage: " PROGRAM " cat [OPTION]... [ID]...\n",
     .desc_short = "Concatenate task unit values.\n",
     .desc_long = "\n\
    Options:\n\
      -d DESK desk name (default is current)\n\
      -e ENV  environment name (default is current)\n\
      -h      show this help and exit\n\
      -k KEY  key to show (builtin or plugin)\n\
      -q      do not write anything to standard error output\n\
    \n\
    Arguments:\n\
      DESK    desk name (default is current)\n\
      ID      task ID (default is current)\n\
      KEY     unit key to show\n\
      ENV     environment name (default is current)\n\
    \n\
    Exit status:\n\
    Under development\n"},
    {
     .tag = TAGBASIC,
     .name = "cd",
     .synop = "Usage: " PROGRAM " cd [OPTION]... [ID]...\n",
     .desc_short = "Switch to task.\n",
     .desc_long = "\n\
    Swtich to task ID. The default ID is the current task ID.\n\
    If ID is \"-\", switch to previous task ID, if exists.\n\
    Alias \"-\" cannot be used with other task IDs. Doudle '-'\n\
    cannot be passed either.\n\
    \n\
    Options:\n\
      -d DESK desk name (default is current)\n\
      -e ENV  environment name (default is current)\n\
      -n      do not update toggles\n\
      -h      show this help and exit\n\
      -q      do not write anything to standard error output\n\
      -N      neither update toggles nor switch to task directory\n\
    \n\
    Arguments:\n\
      DESK    desk name (default current)\n\
      ID      task ID (default is current)\n\
      ENV     environment name (default current)\n\
    \n\
    Exit status:\n\
    The return code is zero, unless invalid option passed, one of the task ID\n\
    is invalid or one the hooks falied to execute (if hooks used).\n"},
    {
     .tag = TAGBASIC,
     .name = "ls",
     .synop = "Usage: " PROGRAM " ls [OPTION]... [ENV]...\n",
     .desc_short = "List environment tasks.\n",
     .desc_long = "\n\
    Options:\n\
      -a      list all tasks (including done)\n\
      -c COL  list tasks on specific column\n\
      -d DESK desk name (default is current)\n\
      -h      show this help and exit\n\
      -q      do not write anything to standard error output\n\
      -v      under development: show more verbose output\n\
      -t      show ONLY toggle switches (current and previous)\n\
      -H      show headers\n\
    \n\
    Arguments:\n\
      DESK    desk name (default is current)\n\
      COL     column name\n\
      ENV     environment name (default is current)\n\
    \n\
    Exit status:\n\
    Under development\n"},
    {
     .tag = TAGBASIC,
     .name = "mv",
     .synop = "Usage: " PROGRAM " mv [OPTION]... [SRC]... DST\n",
     .desc_short = "Move (rename) tasks.\n",
     .desc_long = "\n\
    Options:\n\
      -f      overwrite destination task (under development)\n\
      -h      show this help and exit\n\
      -t DST  move all tasks to target desk (under development)\n\
    \n\
    Arguments:\n\
      DST     destination task ID or destination desk\n\
      SRC     source task ID\n\
    \n\
    Arguments structure:\n\
      SRC -> env/desk/taskid\n\
      .   -> current task ID (if exists)\n\
      ..  -> previous task ID (if exists)\n\
    \n\
    Exit status:\n\
    Under development\n"},
    {
     .tag = TAGBASIC,
     .name = "rm",
     .synop = "Usage: " PROGRAM " rm [OPTION]... [ID]...\n",
     .desc_short = "Remove task from environment.\n",
     .desc_long = "\n\
    Options:\n\
      -d DESK desk name (default is current)\n\
      -e ENV  environment name (default is current)\n\
      -h      show this help and exit\n\
      -q      do not write anything to standard error output\n\
      -y      remove task without confirmation\n\
      -v      explain what is being done\n\
    \n\
    Arguments:\n\
      DESK    desk name (default is current)\n\
      ID      task ID (default is current)\n\
      ENV     environment name (default is current)\n\
    \n\
    Exit status:\n\
    Under development\n"},
    {
     .tag = TAGBASIC,
     .name = "set",
     .synop = "Usage: " PROGRAM " set OPTION... [ID]...\n",
     .desc_short = "Set task unit values.\n",
     .desc_long = "\n\
    Options:\n\
      -d DESK desk name (default is current)\n\
      -e ENV  environment name (default is current)\n\
      -h      show this help and exit\n\
      -i      set unit values in interactive mode (under development)\n\
      -q      do not write anything to standard error output\n\
      -t      task type\n\
      -D      task description\n\
      -P      task priority\n\
    \n\
    Arguments:\n\
      DESK    desk name (default is current)\n\
      ID      task ID (default is current)\n\
      ENV     environment name (default is current)\n\
    \n\
    Values:\n\
      Type    task, bugfix, feature, hotfix\n\
      Prio    lowest, low, mid, high, highest\n\
    \n\
    Exit status:\n\
    Under development\n"},

    {
     .tag = TAGOBJ,
     .name = "cfg",
     .synop = "Usage: " PROGRAM " cfg SUBCMD [OPTION]... ARGS\n",
     .desc_short = "Manage and show configs (under development).\n",
     .desc_long = "\n\
    Arguments:\n\
      SUBCMD  cfg subcommand\n\
    \n\
    Subcommands:\n\
      get     Get config values(under development)\n\
      list    List config values (under development)\n\
      set     Set config values (under development)\n\
      revert  Revert config values (under development)\n\
      save    Save config values into file (under development)\n\
    \n\
    Note:\n\
      Use '" PROGRAM " help cfg-SUBCMD' to get help on subcommands. \n\
      For example: " PROGRAM " help cfg-list\n\
    \n\
    Exit status:\n\
    The return status is return status of subcommand.\n"},

    {
     .tag = TAGOBJ,
     .name = "desk",
     .synop = "Usage: " PROGRAM " desk SUBCMD [OPTION]... ARGS\n",
     .desc_short = "Manage and show desks.\n",
     .desc_long = "\n\
    Arguments:\n\
      SUBCMD  desk subcommand\n\
    \n\
    Subcommands:\n\
      add     Add a new desk\n\
      cat     Concatenate desks info (under development)\n\
      cd      Switch to desk\n\
      ls      List desks\n\
      mv      Move (rename) desks\n\
      prev    Switch to previous desks\n\
      rm      Remove desk with all tasks\n\
      set     Set desks vaules\n\
    \n\
    Note:\n\
      Use '" PROGRAM " help desk-SUBCMD' to get help on subcommands. \n\
      For example: " PROGRAM " help desk-add\n\
    \n\
    Exit status:\n\
    The return status is return status of subcommand.\n"},
    {
     .tag = TAGOBJCMD,
     .name = "desk-add",
     .synop = "Usage: " PROGRAM " desk add [OPTION]... [NAME]...\n",
     .desc_short = "Add new desk.\n",
     .desc_long = "\n\
    Options:\n\
      -e ENV  environment name (default is current)\n\
      -h      show this help and exit\n\
      -n      do not switch to newly created environment\n\
      -q      do not write anything to standard error output\n\
    \n\
    Arguments:\n\
      NAME    desk name (autogenerated if not passed)\n\
    \n\
    Exit status:\n\
    Under development.\n"},
    {
     .tag = TAGOBJCMD,
     .name = "desk-ls",
     .synop = "Usage: " PROGRAM " desk ls [OPTION]... [ENV] \n",
     .desc_short = "List desks.\n",
     .desc_long = "\n\
    Options:\n\
      -h      show this help and exit\n\
      -q      do not write anything to standard error output\n\
    \n\
    Arguments:\n\
      ENV     environment name (default is current)\n\
    \n\
    Exit status:\n\
    Under development.\n"},
    {
     .tag = TAGOBJCMD,
     .name = "desk-mv",
     .synop = "Usage: " PROGRAM " desk mv [OPTION]... [SRC|DST]\n",
     .desc_short = "Move or renome desk.\n",
     .desc_long = "\n\
    Options:\n\
      -e ENV  environment name (default is current)\n\
      -h      show this help and exit\n\
      -q      do not write anything to standard error output\n\
    \n\
    Exit status:\n\
    Under development.\n"},
    {
     .tag = TAGOBJCMD,
     .name = "desk-prev",
     .synop = "Usage: " PROGRAM " desk prev [OPTION]...\n",
     .desc_short = "Switch to previous desk in current environment.\n",
     .desc_long = "\n\
    Options:\n\
      -e ENV  environment name (default is current)\n\
      -h      show this help and exit\n\
      -q      do not write anything to standard error output\n\
    \n\
    Arguments:\n\
      DESK    desk name (default is current)\n\
      ENV     environment name (default is current)\n\
    \n\
    Exit status:\n\
    Under development\n"},
    {
     .tag = TAGOBJCMD,
     .name = "desk-rm",
     .synop = "Usage: " PROGRAM " desk rm [OPTION]... [NAME]...\n",
     .desc_short = "Remove desk(s) from environment.\n",
     .desc_long = "\n\
    Options:\n\
      -e ENV  environment name (default is current)\n\
      -h      show this help and exit\n\
      -n      remove task without confirmation\n\
      -q      do not write anything to standard error output\n\
    \n\
    Arguments:\n\
      NAME    desk name (autogenerated if not passed)\n\
    \n\
    Exit status:\n\
    Under development.\n"},
    {
     .tag = TAGOBJCMD,
     .name = "desk-set",
     .synop = "Usage: " PROGRAM " desk set OPTION... [DESK]...\n",
     .desc_short = "Set task unit values.\n",
     .desc_long = "\n\
    Options:\n\
      -e ENV  environment name (default is current)\n\
      -d      task description\n\
      -h      show this help and exit\n\
      -q      do not write anything to standard error output\n\
    \n\
    Arguments:\n\
      DESK    desk name (default is current)\n\
      ENV     environment name (default is current)\n\
    \n\
    Exit status:\n\
    Under development\n"},
    {
     .tag = TAGOBJCMD,
     .name = "desk-cat",
     .synop = "Usage: " PROGRAM " desk cat [OPTION]... [DESK]...\n",
     .desc_short = "Concatenate desk unit values.\n",
     .desc_long = "\n\
    Options:\n\
      -d DESK desk name (default is current)\n\
      -e ENV  environment name (default is current)\n\
      -h      show this help and exit\n\
      -k KEY  key to show (builtin or plugin)\n\
      -q      do not write anything to standard error output\n\
    \n\
    Arguments:\n\
      DESK    desk name (default is current)\n\
      ID      task ID (default is current)\n\
      KEY     unit key to show\n\
      ENV     environment name (default is current)\n\
    \n\
    Exit status:\n\
    Under development\n"},
    {
     .tag = TAGOBJCMD,
     .name = "desk-cd",
     .synop = "Usage: " PROGRAM " desk cd [OPTION]... [DESK]...\n",
     .desc_short = "Switch to desk.\n",
     .desc_long = "\n\
    Options:\n\
      -e ENV  environment name (default is current)\n\
      -h      show this help and exit\n\
      -n      do not switch to task\n\
      -q      do not write anything to standard error output\n\
    \n\
    Arguments:\n\
      DESK    desk name (default is current)\n\
      ID      task ID (default is current)\n\
      ENV     environment name (default is current)\n\
    \n\
    Exit status:\n\
    Under development\n"},
    {
     .tag = TAGOBJ,
     .name = "column",
     .synop = "Usage: " PROGRAM " column SUBCMD [OPTION]... ARGS\n",
     .desc_short = "Manage and show columns.\n",
     .desc_long = "\n\
    Arguments:\n\
      SUBCMD  column subcommand\n\
    \n\
    Subcommands:\n\
      ls      List columns\n\
      move    Move task to column\n\
    \n\
    Note:\n\
      Use '" PROGRAM " help column-SUBCMD' to get help on subcommands. \n\
      For example: " PROGRAM " help column-list\n\
    \n\
    Exit status:\n\
    The return status is return status of subcommand.\n"},
    {
     .tag = TAGOBJCMD,
     .name = "column-ls",
     .synop = "Usage: " PROGRAM " column ls [OPTION]...\n",
     .desc_short = "List columns.\n",
     .desc_long = "\n\
    \n\
    Exit status:\n\
    Under development.\n"},
    {
     .tag = TAGOBJCMD,
     .name = "column-move",
     .synop = "Usage: " PROGRAM " column move [OPTION]... [ID]...\n",
     .desc_short = "Move task to column.\n",
     .desc_long = "\n\
    \n\
    Options:\n\
      -d DESK desk name (default is current)\n\
      -e ENV  environment name (default is current)\n\
      -c COL  column to move task to\n\
      -h      show this help and exit\n\
      -q      do not write anything to standard error output\n\
    \n\
    Arguments:\n\
      DESK    desk name (default is current)\n\
      COL     column name\n\
      ID      task ID, if none passed then generated by util\n\
      ENV     environment name (default is current)\n\
    \n\
    Exit status:\n\
    Under development.\n"},

    {
     .tag = TAGOBJ,
     .name = "env",
     .synop = "Usage: " PROGRAM " env SUBCMD [OPTION]... ARGS\n",
     .desc_short = "Manage and show environments.\n",
     .desc_long = "\n\
    Arguments:\n\
      SUBCMD  environment subcommand\n\
    \n\
    Subcommands:\n\
      add     Add a new environment\n\
      cat     Concatenate environment info (under development)\n\
      cd      Switch to environment\n\
      ls      List environments\n\
      prev    Switch to previous environment\n\
      rename  Rename environment\n\
      rm      Remove environment with all desks and tasks\n\
      set     Set environment vaules\n\
    \n\
    Note:\n\
      Use '" PROGRAM " help env-SUBCMD' to get help on subcommands. \n\
      For example: " PROGRAM " help env-add\n\
    \n\
    Exit status:\n\
    The return status is return status of subcommand.\n"},
    {
     .tag = TAGOBJCMD,
     .name = "env-add",
     .synop = "Usage: " PROGRAM " env add [OPTION]... [NAME]...\n",
     .desc_short = "Add new environment(s).\n",
     .desc_long = "\n\
    Options:\n\
      -d      desk name (default is 'desk-000')\n\
      -h      show this help and exit\n\
      -n      do not switch to newly created environment\n\
      -q      do not write anything to standard error output\n\
    \n\
    Arguments:\n\
      NAME    environment name (default is current)\n\
    \n\
    Exit status:\n\
    Under development.\n"},
    {
     .tag = TAGOBJCMD,
     .name = "env-cat",
     .synop = "Usage: " PROGRAM " env cat [OPTION]... [NAME]...\n",
     .desc_short = "Concatenate environment(s) info.\n",
     .desc_long = "\n\
    \n\
    Options:\n\
      -h      show this help and exit\n\
      -q      do not write anything to standard error output\n\
    \n\
    Arguments:\n\
      NAME    environment name (default current)\n\
    \n\
    Exit status:\n\
    Under development.\n"},
    {
     .tag = TAGOBJCMD,
     .name = "env-cd",
     .synop = "Usage: " PROGRAM " env cd [OPTION]... [NAME]...\n",
     .desc_short = "Switch to environment.\n",
     .desc_long = "\n\
    Options:\n\
      -h      show this help and exit\n\
      -n      do not switch to environment\n\
      -q      do not write anything to standard error output\n\
    \n\
    Arguments:\n\
      NAME    environment name (default current)\n\
    \n\
    Exit status:\n\
    Under development.\n"},
    {
     .tag = TAGOBJCMD,
     .name = "env-ls",
     .synop = "Usage: " PROGRAM " env ls [OPTION]...\n",
     .desc_short = "List environment(s).\n",
     .desc_long = "\n\
    \n\
    Options:\n\
      -h      show this help and exit\n\
      -q      do not write anything to standard error output\n\
      -v      under development: show more info\n\
    \n\
    Exit status:\n\
    Under development.\n"},
    {
     .tag = TAGOBJCMD,
     .name = "env-prev",
     .synop = "Usage: " PROGRAM " env prev\n",
     .desc_short = "Switch to previous environment.\n",
     .desc_long = "\n\
    Arguments:\n\
      NAME    environment name (default is current)\n\
    \n\
    Exit status:\n\
    Under development.\n"},
    {
     .tag = TAGOBJCMD,
     .name = "env-rename",
     .synop = "Usage: " PROGRAM " env rename [OPTION]... SRC DST\n",
     .desc_short = "Rename environment.\n",
     .desc_long = "\n\
    Options:\n\
      -h      show this help and exit\n\
      -q      do not write anything to standard error output\n\
    \n\
    Arguments:\n\
      SRC    source environment name\n\
      DST    destination environment name\n\
    \n\
    Exit status:\n\
    Under development.\n"},
    {
     .tag = TAGOBJCMD,
     .name = "env-rm",
     .synop = "Usage: " PROGRAM " env rm [OPTION]... [NAME]...\n",
     .desc_short = "Remove environment(s).\n",
     .desc_long = "\n\
    Options:\n\
      -h      show this help and exit\n\
      -n      delete environment without confirmation\n\
      -q      do not write anything to standard error output\n\
    \n\
    Arguments:\n\
      NAME    environment name (default current)\n\
    \n\
    Exit status:\n\
    Under development.\n"},
    {
     .tag = TAGOBJCMD,
     .name = "env-set",
     .synop = "Usage: " PROGRAM " env set [OPTION]... [NAME]...\n",
     .desc_short = "Set environment unit values.\n",
     .desc_long = "\n\
    Arguments:\n\
      NAME    environment name (default is current)\n\
    \n\
    Options:\n\
      -h      show this help and exit\n\
      -q      do not write anything to standard error output\n\
      -D      environment description\n\
    \n\
    Exit status:\n\
    Under development.\n"},
};

static void show_cmd_section(const char *title, const char *tag)
{
    const char *name, *desc;

    printf("\n" PADDING "%s:\n", title);
    for (int i = 0; i < ARRAY_SIZE(helptab); ++i) {
        if (strcmp(helptab[i].tag, tag) == 0) {
            name = helptab[i].name;
            desc = helptab[i].desc_short;
            printf(PADDING "  %-" xstr(CMDSIZ) "s - %s", name, desc);
        }
    }
}

int help_list_commands(void)
{
    printf("Usage: " PROGRAM " [OPTION]... COMMAND|PLUGIN\n");
    printf(PADDING "Run '" PROGRAM " help " PROGRAM "' to get more info.\n");

    show_cmd_section("System", TAGSYSTEM);
    show_cmd_section("Basic", TAGBASIC);
    show_cmd_section("Object", TAGOBJ);
    return 0;
}

int help_usage(const char *cmd)
{
    for (int i = 0; i < ARRAY_SIZE(helptab); ++i) {
        if (strcmp(helptab[i].name, cmd) == 0) {
            printf("%s", helptab[i].synop);
            printf("Try '" PROGRAM " help %s' for more info.\n", cmd);
            return 0;
        }
    }
    return elog(1, "%s: command not found", cmd);
}

int help_lookup(const char *cmd)
{
    int i, found;

    found = false;
    for (i = 0; i < ARRAY_SIZE(helptab); ++i) {
        if (strcmp(helptab[i].name, cmd) == 0) {
            found = true;
            if (helpctx.synop) {
                printf("%s", helptab[i].synop);
                continue;
            }
            if (helpctx.desc_short) {
                printf("%s - %s", cmd, helptab[i].desc_short);
                continue;
            }

            printf("%s", helptab[i].synop);
            printf("    %s", helptab[i].desc_short);
            printf("    %s", helptab[i].desc_long);
            break;
        }
    }
    return found == true ? 0 : 1;
}

int tec_cli_help(int argc, char **argv, tec_ctx_t *ctx)
{
    char c;
    int i, status;

    status = LIBTEC_OK;
    while ((c = getopt(argc, argv, ":ds")) != -1) {
        switch (c) {
        case 'd':
            helpctx.desc_short = true;
            helpctx.synop = false;
            helpctx.desc_long = false;
            break;
        case 's':
            helpctx.synop = true;
            helpctx.desc_short = false;
            helpctx.desc_long = false;
            break;
        case ':':
            return elog(1, "option `-%c' requires an argument", optopt);
        default:
            return elog(1, "invalid option `-%c'", optopt);
        };
    }

    if (optind == argc)
        return help_list_commands();

    for (i = optind; i < argc; ++i)
        if ((status = help_lookup(argv[i])))
            elog(1, "'%s': no such builtin command", argv[i]);
    return status;
}
